import React, { useState } from "react";

const API_URL = (import.meta.env.VITE_API_URL || "http://localhost:8000").replace(/\/$/, "");
const COPY = {
 en:{eyebrow:"SERVER TRAINING · PYTHON",title:"Train on uploaded data",intro:"Upload a labeled CSV. The Python server detects numeric and categorical features, handles missing values, performs a stratified 80/20 split, and trains a new model for that dataset.",note:"CSV must contain label (0 = normal, 1 = attack). Server limits: up to 700 MB, 500,000 rows and 1,000 columns. Prediction data must use the same feature schema as the dataset used for training.",model:"Model",trainingCsv:"Training dataset",choose:"Choose CSV",train:"Train model",training:"Training…",trained:"Training complete",cleaned:"Rows after cleaning",features:"Input features",split:"Train / test",time:"Training time",prediction:"Predict with this model",predictionDesc:"Upload new rows with the same feature columns. label/type are optional for prediction.",predictionCsv:"Prediction dataset",predict:"Run prediction",predicting:"Predicting…",analyzed:"Analyzed",normal:"Normal",anomalous:"Anomalous",rate:"Anomaly rate",result:"Prediction result"},
 sr:{eyebrow:"SERVER TRENING · PYTHON",title:"Treniranje nad uploadovanim podacima",intro:"Otpremi označeni CSV. Python server automatski prepoznaje numerička i kategorijska obeležja, obrađuje nedostajuće vrednosti, pravi stratifikovanu podelu 80/20 i trenira novi model za taj skup.",note:"CSV mora da sadrži label (0 = normalno, 1 = napad). Serverski limiti su 700 MB, 500.000 redova i 1.000 kolona. Za predikciju se koristi CSV sa istom strukturom obeležja kao skup na kom je model treniran.",model:"Model",trainingCsv:"Skup za trening",choose:"Izaberi CSV",train:"Treniraj model",training:"Treniranje…",trained:"Trening završen",cleaned:"Redova posle čišćenja",features:"Ulazna obeležja",split:"Trening / test",time:"Vreme treninga",prediction:"Predikcija ovim modelom",predictionDesc:"Otpremi nove redove sa istim kolonama obeležja. label/type nisu obavezni za predikciju.",predictionCsv:"Skup za predikciju",predict:"Pokreni predikciju",predicting:"Predikcija…",analyzed:"Analizirano",normal:"Normalno",anomalous:"Anomalno",rate:"Udeo anomalija",result:"Rezultat predikcije"}
};
export default function ServerTrainingPanel({lang="en"}){
 const t=COPY[lang]||COPY.en;
 const [trainFile,setTrainFile]=useState(null),[predictFile,setPredictFile]=useState(null),[modelType,setModelType]=useState("random_forest");
 const [training,setTraining]=useState(false),[predicting,setPredicting]=useState(false),[trainResult,setTrainResult]=useState(null),[prediction,setPrediction]=useState(null),[error,setError]=useState("");
 const readError=async r=>{try{const d=await r.json();return d.detail||JSON.stringify(d)}catch{return `${r.status} ${r.statusText}`}};
 const train=async()=>{if(!trainFile)return;setTraining(true);setError("");setTrainResult(null);setPrediction(null);const f=new FormData();f.append("file",trainFile);f.append("model_type",modelType);try{const r=await fetch(`${API_URL}/api/train`,{method:"POST",body:f});if(!r.ok)throw new Error(await readError(r));setTrainResult(await r.json())}catch(e){setError(e.message)}finally{setTraining(false)}};
 const predict=async()=>{if(!predictFile||!trainResult?.model_id)return;setPredicting(true);setError("");setPrediction(null);const f=new FormData();f.append("model_id",trainResult.model_id);f.append("file",predictFile);try{const r=await fetch(`${API_URL}/api/predict`,{method:"POST",body:f});if(!r.ok)throw new Error(await readError(r));setPrediction(await r.json())}catch(e){setError(e.message)}finally{setPredicting(false)}};
 return <div className="space-y-5">
  <section className="relative overflow-hidden rounded-2xl border border-blue-500/20 bg-white dark:bg-slate-900"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-blue-500 via-cyan-400 to-teal-400"/><div className="p-5 sm:p-7">
   <div className="text-[11px] font-mono tracking-[0.18em] text-blue-600 dark:text-blue-400 mb-2">{t.eyebrow}</div><h2 className="text-xl sm:text-2xl font-semibold">{t.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-400">{t.intro}</p>
   <div className="mt-5 grid gap-4 md:grid-cols-[220px_1fr]"><label><span className="text-xs font-mono uppercase text-slate-500">{t.model}</span><select value={modelType} onChange={e=>setModelType(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 px-3 py-3 text-sm"><option value="random_forest">Random Forest</option><option value="xgboost">XGBoost</option></select></label><FileBox label={t.trainingCsv} file={trainFile} choose={t.choose} onChange={e=>setTrainFile(e.target.files?.[0]||null)}/></div>
   <div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 px-4 py-3 text-xs leading-5 text-amber-800 dark:text-amber-300">{t.note}</div>
   {error&&<div className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-sm text-rose-600 dark:text-rose-400">{error}</div>}
   <button onClick={train} disabled={!trainFile||training} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-40">{training&&<span className="h-4 w-4 animate-spin rounded-full border-2 border-white/30 border-t-white"/>}{training?t.training:t.train}</button>
  </div></section>
  {trainResult&&<section className="rounded-2xl border border-emerald-500/20 bg-white dark:bg-slate-900 p-5 sm:p-7"><div className="flex items-start justify-between gap-3 flex-wrap"><div><div className="text-[11px] font-mono uppercase tracking-widest text-emerald-600 dark:text-emerald-400">{t.trained}</div><div className="mt-1 text-xs font-mono text-slate-500">model {trainResult.model_id} · {trainResult.model_type.replace("_"," ")}</div></div><div className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-mono text-emerald-700 dark:text-emerald-400">F1 {(trainResult.metrics.f1*100).toFixed(2)}%</div></div>
   <div className="mt-5 grid grid-cols-2 lg:grid-cols-6 gap-3"><Stat label="Accuracy" value={(trainResult.metrics.accuracy*100).toFixed(2)+"%"}/><Stat label="Precision" value={(trainResult.metrics.precision*100).toFixed(2)+"%"}/><Stat label="Recall" value={(trainResult.metrics.recall*100).toFixed(2)+"%"}/><Stat label="ROC-AUC" value={trainResult.metrics.roc_auc.toFixed(5)}/><Stat label={t.cleaned} value={trainResult.cleaned_rows.toLocaleString()}/><Stat label={t.features} value={trainResult.metrics.raw_feature_count}/></div>
   <div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs font-mono text-slate-500"><span>{t.split}: <b>{trainResult.metrics.n_train.toLocaleString()} / {trainResult.metrics.n_test.toLocaleString()}</b></span><span>{t.time}: <b>{trainResult.metrics.train_time_sec}s</b></span><span>numeric / categorical: <b>{trainResult.metrics.numeric_features} / {trainResult.metrics.categorical_features}</b></span></div>
  </section>}
  {trainResult&&<section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-7"><h3 className="text-lg font-semibold">{t.prediction}</h3><p className="mt-1 text-sm text-slate-500">{t.predictionDesc}</p><div className="mt-4 flex flex-col sm:flex-row gap-3 sm:items-end"><div className="flex-1"><FileBox label={t.predictionCsv} file={predictFile} choose={t.choose} onChange={e=>setPredictFile(e.target.files?.[0]||null)}/></div><button onClick={predict} disabled={!predictFile||predicting} className="rounded-xl border border-blue-500 px-5 py-3 text-sm font-semibold text-blue-600 dark:text-blue-400 disabled:opacity-40">{predicting?t.predicting:t.predict}</button></div>
   {prediction&&<div className="mt-5"><div className="text-[11px] font-mono uppercase tracking-widest text-slate-500 mb-3">{t.result}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Stat label={t.analyzed} value={prediction.rows.toLocaleString()}/><Stat label={t.normal} value={prediction.normal.toLocaleString()}/><Stat label={t.anomalous} value={prediction.anomalous.toLocaleString()}/><Stat label={t.rate} value={(prediction.anomaly_rate*100).toFixed(1)+"%"}/></div></div>}
  </section>}
 </div>
}
function FileBox({label,file,choose,onChange}){return <label className="block"><span className="text-xs font-mono uppercase text-slate-500">{label}</span><div className="mt-2 flex min-h-[48px] items-center gap-3 rounded-xl border border-dashed border-slate-300 dark:border-slate-700 bg-slate-50 dark:bg-slate-950 px-3 py-2"><span className="rounded-lg bg-slate-200 dark:bg-slate-800 px-3 py-1.5 text-xs font-semibold">{choose}</span><span className="min-w-0 truncate text-xs font-mono text-slate-500">{file?.name||"CSV"}</span><input type="file" accept=".csv,text/csv" onChange={onChange} className="hidden"/></div></label>}
function Stat({label,value}){return <div className="rounded-xl bg-slate-50 dark:bg-slate-800/60 px-3 py-3"><div className="text-[10px] font-mono uppercase text-slate-500">{label}</div><div className="mt-1 text-lg font-semibold">{value}</div></div>}
